version: "3.8"

services:
    webserver:
        container_name: ecommerce-serve
        build: .
        restart: always
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_DATABASE=ecommerce_db
            - DB_USERNAME=root
            - DB_PASSWORD=root
        extra_hosts:
            - "ecommerce.test:host-gateway"

    db:
        container_name: ecommerce-mysql
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ecommerce_db
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        container_name: ecommerce-phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8082:80"

volumes:
    mysql_data:
